version: "3.9"

services:
  app:
    build: .
    container_name: express-compose-app
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: