version: '3'

services:

  flask-app:
    build:
      context: ./docker_flask
    ports:
      - "5000:5000"

  express-app:
    build:
      context: ./docker_express
    ports:
      - "3000:3000"